// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yiso.Game {

  /// <summary>Holder for reflection information generated from game_enum.proto</summary>
  public static partial class GameEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for game_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9nYW1lX2VudW0ucHJvdG8SCXlpc28uZ2FtZSqmAgoKUGFja2V0VHlwZRIL",
            "CgdVTktOT1dOEAASDAoIQzJTX0NIQVQQARIPCgtDMlNfV0hJU1BFUhACEhMK",
            "D0MyU19DUkVBVEVfUk9PTRADEhMKD0MyU19ERUxFVEVfUk9PTRAEEhEKDUMy",
            "U19KT0lOX1JPT00QBRISCg5DMlNfTEVBVkVfUk9PTRAGEhEKDUMyU19ST09N",
            "X0NIQVQQBxINCghTMkNfQ0hBVBDpBxIQCgtTMkNfV0hJU1BFUhDqBxIUCg9T",
            "MkNfQ1JFQVRFX1JPT00Q6wcSFAoPUzJDX0RFTEVURV9ST09NEOwHEhIKDVMy",
            "Q19KT0lOX1JPT00Q7QcSEwoOUzJDX0xFQVZFX1JPT00Q7gcSEgoNUzJDX1JP",
            "T01fQ0hBVBDvB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Yiso.Game.PacketType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 패킷 타입 (TCP 헤더의 packet_type 필드와 동일한 값)
  /// C2S: 1~999, S2C: 1000~
  /// </summary>
  public enum PacketType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// Client -> Server
    /// </summary>
    [pbr::OriginalName("C2S_CHAT")] C2SChat = 1,
    [pbr::OriginalName("C2S_WHISPER")] C2SWhisper = 2,
    [pbr::OriginalName("C2S_CREATE_ROOM")] C2SCreateRoom = 3,
    [pbr::OriginalName("C2S_DELETE_ROOM")] C2SDeleteRoom = 4,
    [pbr::OriginalName("C2S_JOIN_ROOM")] C2SJoinRoom = 5,
    [pbr::OriginalName("C2S_LEAVE_ROOM")] C2SLeaveRoom = 6,
    [pbr::OriginalName("C2S_ROOM_CHAT")] C2SRoomChat = 7,
    /// <summary>
    /// Server -> Client
    /// </summary>
    [pbr::OriginalName("S2C_CHAT")] S2CChat = 1001,
    [pbr::OriginalName("S2C_WHISPER")] S2CWhisper = 1002,
    [pbr::OriginalName("S2C_CREATE_ROOM")] S2CCreateRoom = 1003,
    [pbr::OriginalName("S2C_DELETE_ROOM")] S2CDeleteRoom = 1004,
    [pbr::OriginalName("S2C_JOIN_ROOM")] S2CJoinRoom = 1005,
    [pbr::OriginalName("S2C_LEAVE_ROOM")] S2CLeaveRoom = 1006,
    [pbr::OriginalName("S2C_ROOM_CHAT")] S2CRoomChat = 1007,
  }

  #endregion

}

#endregion Designer generated code
